Avoid dlna error because of faulty plugin or DLNAResource. This change allows pms to work normally with correctly configured DLNAResources and to not add ones that are faulty. For this a try/catch block has been added in DLNAResource.addChild. A stack trace will show the origin of the problem. It also surrounds every call to an external interface implementation (ExternalListener etc) with a try/catch. Throwable is being caught everywhere to catch exceptions as well as errors (e.g. java.lang.NoSuchMethodError occurring now with the removed methods)